# Generated by Django 4.2.29 on 2026-05-25 22:39

import django.core.validators
from django.db import migrations

import shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0015_document_category_system_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="ssn",
            field=shared.fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted at rest. Display masked by default.",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SSN must be exactly 9 digits.", regex="^\\d{9}$"
                    )
                ],
            ),
        ),
    ]
