# Generated by Django 4.2.29 on 2026-05-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0017_encrypt_existing_ssns"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["facility", "last_name", "first_name"],
                name="patient_facility_name",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["facility", "date_of_birth"], name="patient_facility_dob"
            ),
        ),
    ]
