# Generated by Django 4.2.29 on 2026-07-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_seed_system_org_roles"),
        ("facilities", "0026_audit_documents_delete_permissions"),
        ("patients", "0018_add_patient_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="owning_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_pharmacies",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="owning_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_pharmacies",
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("owning_facility__isnull", False),
                    ("owning_organization__isnull", False),
                    _negated=True,
                ),
                name="pharmacy_has_at_most_one_tenant_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("directory_source", "external_id"),
                name="unique_pharmacy_external_directory_id",
            ),
        ),
    ]
