# Generated by Django 4.2.29 on 2026-05-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0013_appointment_is_billable"),
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinical_encounter",
                to="appointments.appointment",
            ),
        ),
    ]
