# Generated by Django 4.2.29 on 2026-05-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0014_bookableslot"),
        ("clinical", "0003_vitals_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinical_encounter",
                to="appointments.appointment",
            ),
        ),
    ]
