# Generated by Django 4.2.29 on 2026-05-22 01:55

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0015_document_category_system_defaults"),
        ("facilities", "0014_billing_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterBillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("coding_needed", "Coding Needed"),
                            ("ready_to_submit", "Ready to Submit"),
                            ("claim_created", "Claim Created"),
                        ],
                        default="coding_needed",
                        max_length=32,
                    ),
                ),
                ("payer_name", models.CharField(blank=True, max_length=150)),
                (
                    "place_of_service",
                    models.CharField(blank=True, default="11", max_length=2),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_billing_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_record",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_billing_records",
                        to="facilities.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounter_billing_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_billing_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EncounterDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="billing.encounterbillingrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="EncounterChargeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_code", models.CharField(max_length=16)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("modifier_1", models.CharField(blank=True, max_length=2)),
                ("modifier_2", models.CharField(blank=True, max_length=2)),
                ("modifier_3", models.CharField(blank=True, max_length=2)),
                ("modifier_4", models.CharField(blank=True, max_length=2)),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=6
                    ),
                ),
                (
                    "charge_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("diagnosis_pointers", models.JSONField(blank=True, default=list)),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_lines",
                        to="billing.encounterbillingrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="encounterdiagnosis",
            constraint=models.UniqueConstraint(
                fields=("billing_record", "sequence"),
                name="unique_billing_diagnosis_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="encounterchargeline",
            constraint=models.UniqueConstraint(
                fields=("billing_record", "sequence"),
                name="unique_billing_charge_line_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="encounterbillingrecord",
            index=models.Index(
                fields=["facility", "patient", "-updated_at"],
                name="billing_enc_facilit_1c3c5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounterbillingrecord",
            index=models.Index(
                fields=["facility", "status", "-updated_at"],
                name="billing_enc_facilit_67a470_idx",
            ),
        ),
    ]
