# Generated by Django 4.2.29 on 2026-05-24 21:23

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0015_medication_allergy_permissions"),
        ("organizations", "0004_organizationpharmacypreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationFeeScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_code", models.CharField(max_length=16)),
                ("description", models.CharField(max_length=255)),
                (
                    "default_units",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=6
                    ),
                ),
                ("charge_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modifier_1", models.CharField(blank=True, max_length=2)),
                ("modifier_2", models.CharField(blank=True, max_length=2)),
                ("modifier_3", models.CharField(blank=True, max_length=2)),
                ("modifier_4", models.CharField(blank=True, max_length=2)),
                (
                    "place_of_service",
                    models.CharField(blank=True, default="11", max_length=2),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organization_fee_schedule_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedule_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_organization_fee_schedule_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "service_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="FacilityFeeScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_code", models.CharField(blank=True, max_length=16)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "default_units",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "charge_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("modifier_1", models.CharField(blank=True, max_length=2)),
                ("modifier_2", models.CharField(blank=True, max_length=2)),
                ("modifier_3", models.CharField(blank=True, max_length=2)),
                ("modifier_4", models.CharField(blank=True, max_length=2)),
                ("place_of_service", models.CharField(blank=True, max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_facility_fee_schedule_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedule_overrides",
                        to="facilities.facility",
                    ),
                ),
                (
                    "organization_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_overrides",
                        to="billing.organizationfeescheduleitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_facility_fee_schedule_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "sort_order",
                    "service_code",
                    "organization_item__service_code",
                    "id",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organizationfeescheduleitem",
            index=models.Index(
                fields=["organization", "is_active", "service_code"],
                name="billing_org_organiz_f2167a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeescheduleitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "service_code"),
                name="unique_org_fee_schedule_service_code",
            ),
        ),
        migrations.AddIndex(
            model_name="facilityfeescheduleoverride",
            index=models.Index(
                fields=["facility", "is_active", "service_code"],
                name="billing_fac_facilit_5dab12_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityfeescheduleoverride",
            constraint=models.UniqueConstraint(
                fields=("facility", "organization_item"),
                name="unique_facility_fee_schedule_org_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityfeescheduleoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization_item__isnull", True)),
                fields=("facility", "service_code"),
                name="unique_facility_local_fee_schedule_code",
            ),
        ),
    ]
