# Generated by Django 4.2.29 on 2026-05-25 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_fee_schedules(apps, schema_editor):
    OrganizationFeeSchedule = apps.get_model("billing", "OrganizationFeeSchedule")
    OrganizationFeeScheduleItem = apps.get_model(
        "billing", "OrganizationFeeScheduleItem"
    )

    organization_ids = (
        OrganizationFeeScheduleItem.objects.filter(schedule__isnull=True)
        .values_list("organization_id", flat=True)
        .distinct()
    )
    for organization_id in organization_ids:
        schedule, _ = OrganizationFeeSchedule.objects.get_or_create(
            organization_id=organization_id,
            code="standard",
            defaults={
                "name": "Standard Fee Schedule",
                "assignment_type": "same",
                "is_default": True,
                "is_active": True,
            },
        )
        OrganizationFeeScheduleItem.objects.filter(
            organization_id=organization_id,
            schedule__isnull=True,
        ).update(schedule=schedule)


def remove_default_fee_schedules(apps, schema_editor):
    OrganizationFeeSchedule = apps.get_model("billing", "OrganizationFeeSchedule")
    OrganizationFeeScheduleItem = apps.get_model(
        "billing", "OrganizationFeeScheduleItem"
    )

    standard_schedules = OrganizationFeeSchedule.objects.filter(
        code="standard",
        is_default=True,
    )
    OrganizationFeeScheduleItem.objects.filter(
        schedule__in=standard_schedules,
    ).update(schedule=None)
    standard_schedules.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insurance", "0004_organizationinsurancecarrierpreference_and_more"),
        ("facilities", "0016_facility_custom_operating_hours"),
        ("organizations", "0005_facilitypharmacypreferenceoverride_and_more"),
        ("billing", "0002_organizationfeescheduleitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationFeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=64)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("same", "Use for all billing"),
                            ("payer", "Use for payer"),
                            ("practitioner", "Use for practitioner"),
                        ],
                        default="same",
                        max_length=24,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organization_fee_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_schedules",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="payer_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_schedules",
                to="insurance.organizationinsurancecarrierpreference",
            ),
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_schedules",
                to="facilities.staff",
            ),
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_organization_fee_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationfeescheduleitem",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="billing.organizationfeeschedule",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="organizationfeescheduleitem",
            name="unique_org_fee_schedule_service_code",
        ),
        migrations.RunPython(
            create_default_fee_schedules,
            remove_default_fee_schedules,
        ),
        migrations.AddIndex(
            model_name="organizationfeescheduleitem",
            index=models.Index(
                fields=["schedule", "is_active", "service_code"],
                name="billing_org_schedul_84cd33_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeescheduleitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", False)),
                fields=("schedule", "service_code"),
                name="unique_fee_schedule_sheet_service_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeescheduleitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", True)),
                fields=("organization", "service_code"),
                name="unique_org_fee_schedule_legacy_service_code",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationfeeschedule",
            index=models.Index(
                fields=["organization", "assignment_type", "is_active"],
                name="billing_org_organiz_d3e379_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeeschedule",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_org_fee_schedule_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="unique_org_default_fee_schedule",
            ),
        ),
    ]
