# Generated by Django 4.2.29 on 2026-05-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_migrate_fee_schedule_links"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organizationfeeschedule",
            name="billing_org_organiz_d3e379_idx",
        ),
        migrations.RemoveField(
            model_name="organizationfeeschedule",
            name="assignment_type",
        ),
        migrations.RemoveField(
            model_name="organizationfeeschedule",
            name="payer_preference",
        ),
        migrations.RemoveField(
            model_name="organizationfeeschedule",
            name="practitioner",
        ),
        migrations.AddIndex(
            model_name="organizationfeeschedule",
            index=models.Index(
                fields=["organization", "is_active"],
                name="billing_org_organiz_c3f5a2_idx",
            ),
        ),
    ]
