# Generated by Django 4.2.29 on 2026-05-25 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0017_fee_schedule_redesign"),
        ("billing", "0005_fee_schedule_redesign"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationfeeschedule",
            name="unique_org_fee_schedule_code",
        ),
        migrations.RemoveConstraint(
            model_name="organizationfeeschedule",
            name="unique_org_default_fee_schedule",
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_fee_schedules",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="organizationfeeschedule",
            name="source_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_schedules",
                to="billing.organizationfeeschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationfeeschedule",
            index=models.Index(
                fields=["facility", "is_active"], name="billing_org_facilit_62033a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facility__isnull", True)),
                fields=("organization", "code"),
                name="unique_org_fee_schedule_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facility__isnull", False)),
                fields=("facility", "code"),
                name="unique_facility_fee_schedule_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facility__isnull", True), ("is_default", True)),
                fields=("organization",),
                name="unique_org_default_fee_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facility__isnull", False), ("is_default", True)),
                fields=("facility",),
                name="unique_facility_default_fee_schedule",
            ),
        ),
    ]
