# Generated by Django 4.2.29 on 2026-05-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0015_medication_allergy_permissions"),
        ("patients", "0015_document_category_system_defaults"),
        ("organizations", "0004_organizationpharmacypreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityPharmacyPreferenceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_preference_overrides",
                        to="facilities.facility",
                    ),
                ),
                (
                    "organization_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_overrides",
                        to="organizations.organizationpharmacypreference",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_preference_overrides",
                        to="patients.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "sort_order",
                    "pharmacy__name",
                    "organization_preference__pharmacy__name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="facilitypharmacypreferenceoverride",
            constraint=models.UniqueConstraint(
                fields=("facility", "organization_preference"),
                name="unique_facility_pharmacy_org_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilitypharmacypreferenceoverride",
            constraint=models.UniqueConstraint(
                fields=("facility", "pharmacy"),
                name="unique_facility_local_pharmacy_override",
            ),
        ),
    ]
