# Generated by Django 4.2.29 on 2026-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_facilitypharmacypreferenceoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="security_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
