# Generated by Django 4.2.29 on 2026-05-26 04:52

from django.db import migrations

SYSTEM_ROLES = [
    {
        "code": "owner",
        "name": "Owner",
        "description": "Full organization access and billing control",
    },
    {
        "code": "admin",
        "name": "Admin",
        "description": "Full workspace configuration access",
    },
    {
        "code": "member",
        "name": "Member",
        "description": "Standard clinical access",
    },
]


def seed_system_roles(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationRole = apps.get_model("organizations", "OrganizationRole")

    for org in Organization.objects.all():
        for role in SYSTEM_ROLES:
            OrganizationRole.objects.get_or_create(
                organization=org,
                code=role["code"],
                defaults={
                    "name": role["name"],
                    "description": role["description"],
                    "is_system_role": True,
                    "is_deletable": False,
                    "is_active": True,
                    "security_permissions": {},
                },
            )


def reverse_seed(apps, schema_editor):
    OrganizationRole = apps.get_model("organizations", "OrganizationRole")
    OrganizationRole.objects.filter(is_system_role=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_add_organization_role"),
    ]

    operations = [
        migrations.RunPython(seed_system_roles, reverse_seed),
    ]
