# Generated by Django 4.2.29 on 2026-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0012_appointment_edit_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_billable",
            field=models.BooleanField(default=True),
        ),
    ]
