# Generated by Django 4.2.29 on 2026-05-28 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facilities", "0022_appointmenttype_auto_confirm_bookings_and_more"),
        ("appointments", "0013_appointment_is_billable"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_booked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookable_slot",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "appointment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookable_slots",
                        to="facilities.appointmenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bookable_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookable_slots",
                        to="facilities.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["provider", "is_booked", "start_time"],
                        name="bookable_provider_open_idx",
                    ),
                    models.Index(
                        fields=["appointment_type", "is_booked", "start_time"],
                        name="bookable_type_open_idx",
                    ),
                ],
            },
        ),
    ]
