# Generated by Django 4.2.29 on 2026-06-20 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0026_audit_documents_delete_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0014_bookableslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlotHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("user_display_name", models.CharField(blank=True, max_length=150)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_holds",
                        to="facilities.facility",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_holds",
                        to="facilities.facilityresource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_slot_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "start_time"],
                        name="slot_hold_facility_start_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointmentslothold",
            constraint=models.UniqueConstraint(
                fields=("facility", "resource", "start_time"),
                name="uniq_slot_hold_facility_resource_start",
            ),
        ),
    ]
