# Generated by Django 4.2.29 on 2026-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_appointmentslothold_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointmentslothold",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resource__isnull", True)),
                fields=("facility", "start_time"),
                name="uniq_slot_hold_facility_null_resource_start",
            ),
        ),
    ]
