# Generated by Django 4.2.29 on 2026-05-28 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0022_appointmenttype_auto_confirm_bookings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0018_add_patient_search_indexes"),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefillRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmacy_name", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("patient_note", models.TextField(blank=True, max_length=500)),
                ("clinician_note", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_name", models.CharField(blank=True, max_length=150)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_requests",
                        to="facilities.facility",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refill_requests",
                        to="medications.medication",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refill_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refill_requests",
                        to="patients.pharmacy",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_refill_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "status", "-requested_at"],
                        name="medications_facilit_3692ea_idx",
                    ),
                    models.Index(
                        fields=["patient", "-requested_at"],
                        name="medications_patient_40464c_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="refillrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("medication",),
                name="unique_pending_refill_per_medication",
            ),
        ),
    ]
