# Generated by Django 4.2.29 on 2026-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_refillrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillrequest",
            name="source",
            field=models.CharField(
                choices=[("patient", "Patient"), ("pharmacy", "Pharmacy")],
                default="patient",
                max_length=20,
            ),
        ),
    ]
