# Generated by Django 4.2.29 on 2026-05-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0018_add_patient_search_indexes"),
        ("facilities", "0024_staff_eprescribe_enabled"),
        ("medications", "0003_refillrequest_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="prescriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescribed_medications",
                to="patients.careprovider",
            ),
        ),
        migrations.CreateModel(
            name="PrescriberDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriber_delegations",
                        to="facilities.staff",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriber_delegations",
                        to="facilities.facility",
                    ),
                ),
                (
                    "prescriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="patients.careprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="prescriberdelegation",
            constraint=models.UniqueConstraint(
                fields=("facility", "prescriber", "delegate"),
                name="unique_prescriber_delegation",
            ),
        ),
    ]
