# Generated by Django 4.2.29 on 2026-06-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0004_medication_prescriber_prescriberdelegation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillrequest",
            name="days_supply",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(30, "30 days"), (60, "60 days"), (90, "90 days")],
                null=True,
            ),
        ),
    ]
