# Generated by Codex on 2026-05-21

from django.db import migrations

CLINICAL_PERMISSIONS_BY_ROLE = {
    "admin": {
        "clinical.view": True,
        "clinical.create": True,
        "clinical.update": True,
        "clinical.sign": True,
    },
    "physician": {
        "clinical.view": True,
        "clinical.create": True,
        "clinical.update": True,
        "clinical.sign": True,
    },
    "nurse": {
        "clinical.view": True,
        "clinical.create": True,
        "clinical.update": True,
        "clinical.sign": False,
    },
    "staff": {
        "clinical.view": True,
        "clinical.create": False,
        "clinical.update": False,
        "clinical.sign": False,
    },
    "biller": {
        "clinical.view": False,
        "clinical.create": False,
        "clinical.update": False,
        "clinical.sign": False,
    },
}


def add_clinical_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        role_permissions = CLINICAL_PERMISSIONS_BY_ROLE.get(role.code, {})
        permissions = dict(role.security_permissions or {})
        for key, value in role_permissions.items():
            permissions[key] = value
        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0012_pharmacy_management_permission"),
    ]

    operations = [
        migrations.RunPython(
            add_clinical_permissions,
            migrations.RunPython.noop,
        ),
    ]
