# Generated by Codex on 2026-05-22

from django.db import migrations

BILLING_PERMISSIONS_BY_ROLE = {
    "admin": {
        "billing.view": True,
        "billing.manage": True,
    },
    "physician": {
        "billing.view": True,
        "billing.manage": False,
    },
    "nurse": {
        "billing.view": False,
        "billing.manage": False,
    },
    "staff": {
        "billing.view": False,
        "billing.manage": False,
    },
    "biller": {
        "billing.view": True,
        "billing.manage": True,
    },
}


def add_billing_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        role_permissions = BILLING_PERMISSIONS_BY_ROLE.get(role.code, {})
        permissions = dict(role.security_permissions or {})
        for key, value in role_permissions.items():
            permissions[key] = value
        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0013_clinical_permissions"),
    ]

    operations = [
        migrations.RunPython(
            add_billing_permissions,
            migrations.RunPython.noop,
        ),
    ]
