# Generated by Codex on 2026-05-22

from django.db import migrations

MEDICATION_ALLERGY_PERMISSIONS_BY_ROLE = {
    "admin": {
        "medications.view": True,
        "medications.manage": True,
        "allergies.view": True,
        "allergies.manage": True,
    },
    "physician": {
        "medications.view": True,
        "medications.manage": True,
        "allergies.view": True,
        "allergies.manage": True,
    },
    "nurse": {
        "medications.view": True,
        "medications.manage": True,
        "allergies.view": True,
        "allergies.manage": True,
    },
    "staff": {
        "medications.view": True,
        "medications.manage": False,
        "allergies.view": True,
        "allergies.manage": False,
    },
    "biller": {
        "medications.view": False,
        "medications.manage": False,
        "allergies.view": False,
        "allergies.manage": False,
    },
}


def add_medication_allergy_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        role_permissions = MEDICATION_ALLERGY_PERMISSIONS_BY_ROLE.get(role.code, {})
        permissions = dict(role.security_permissions or {})
        for key, value in role_permissions.items():
            permissions[key] = value
        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0014_billing_permissions"),
    ]

    operations = [
        migrations.RunPython(
            add_medication_allergy_permissions,
            migrations.RunPython.noop,
        ),
    ]
