# Generated by Django 4.2.29 on 2026-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0015_medication_allergy_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="custom_operating_hours",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
