# Generated by Django 4.2.29 on 2026-05-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0017_fee_schedule_redesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="dea_expiration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="dea_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staff",
            name="npi",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="staff",
            name="specialty",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="state_license_expiration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="state_license_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="staff",
            name="state_license_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="staff",
            name="taxonomy_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
