# Generated by Django 4.2.29 on 2026-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0018_physician_credential_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentstatus",
            name="is_billable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appointmenttype",
            name="is_billable",
            field=models.BooleanField(default=True),
        ),
    ]
