# Generated by Codex on 2026-05-26

from django.db import migrations

NEW_PERMISSION_DEFAULTS_BY_ROLE = {
    "admin": {
        "billing.fee_schedules.manage": True,
        "pharmacies.organization.manage": True,
        "pharmacies.facility.manage": True,
    },
    "physician": {
        "billing.fee_schedules.manage": False,
        "pharmacies.organization.manage": False,
        "pharmacies.facility.manage": False,
    },
    "nurse": {
        "billing.fee_schedules.manage": False,
        "pharmacies.organization.manage": False,
        "pharmacies.facility.manage": False,
    },
    "staff": {
        "billing.fee_schedules.manage": False,
        "pharmacies.organization.manage": False,
        "pharmacies.facility.manage": False,
    },
    "biller": {
        "billing.fee_schedules.manage": False,
        "pharmacies.organization.manage": False,
        "pharmacies.facility.manage": False,
    },
}


def split_config_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")
    Staff = apps.get_model("facilities", "Staff")

    for role in StaffRole.objects.all():
        permissions = dict(role.security_permissions or {})
        role_defaults = NEW_PERMISSION_DEFAULTS_BY_ROLE.get(role.code, {})

        for key, default_value in role_defaults.items():
            permissions.setdefault(key, default_value)

        if "billing.fee_schedules.manage" not in permissions:
            permissions["billing.fee_schedules.manage"] = bool(
                permissions.get("admin.facility.manage", False)
            )

        legacy_pharmacy_permission = permissions.get("pharmacies.manage")
        if (
            "pharmacies.organization.manage" not in permissions
            and legacy_pharmacy_permission is not None
        ):
            permissions["pharmacies.organization.manage"] = bool(
                legacy_pharmacy_permission
            )
        if (
            "pharmacies.facility.manage" not in permissions
            and legacy_pharmacy_permission is not None
        ):
            permissions["pharmacies.facility.manage"] = bool(legacy_pharmacy_permission)

        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])

    for staff in Staff.objects.all():
        overrides = dict(staff.security_overrides or {})

        if "billing.fee_schedules.manage" not in overrides:
            billing_override = overrides.get("billing.manage")
            admin_override = overrides.get("admin.facility.manage")
            if admin_override is not None:
                overrides["billing.fee_schedules.manage"] = bool(admin_override)
            elif billing_override is False:
                overrides["billing.fee_schedules.manage"] = False

        legacy_pharmacy_override = overrides.get("pharmacies.manage")
        if (
            "pharmacies.organization.manage" not in overrides
            and legacy_pharmacy_override is not None
        ):
            overrides["pharmacies.organization.manage"] = bool(legacy_pharmacy_override)
        if (
            "pharmacies.facility.manage" not in overrides
            and legacy_pharmacy_override is not None
        ):
            overrides["pharmacies.facility.manage"] = bool(legacy_pharmacy_override)

        staff.security_overrides = overrides
        staff.save(update_fields=["security_overrides"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0020_set_non_billable_statuses"),
    ]

    operations = [
        migrations.RunPython(
            split_config_permissions,
            migrations.RunPython.noop,
        ),
    ]
