# Generated by Django 4.2.29 on 2026-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0021_split_config_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttype",
            name="auto_confirm_bookings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointmenttype",
            name="bookable_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="cancellation_cutoff_hours",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="facility",
            name="online_cancellation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facility",
            name="online_scheduling_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="auto_confirm_bookings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="cancellation_cutoff_hours",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="staff",
            name="online_cancellation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="online_scheduling_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
