# Generated by Claude on 2026-05-28

from django.db import migrations

MESSAGING_PERMISSIONS_BY_ROLE = {
    "admin": {
        "messaging.view": True,
        "messaging.respond": True,
    },
    "physician": {
        "messaging.view": True,
        "messaging.respond": True,
    },
    "nurse": {
        "messaging.view": True,
        "messaging.respond": True,
    },
    "staff": {
        "messaging.view": True,
        "messaging.respond": True,
    },
    "biller": {
        "messaging.view": False,
        "messaging.respond": False,
    },
}


def add_messaging_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        role_permissions = MESSAGING_PERMISSIONS_BY_ROLE.get(role.code, {})
        permissions = dict(role.security_permissions or {})
        for key, default_value in role_permissions.items():
            permissions.setdefault(key, default_value)
        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0022_appointmenttype_auto_confirm_bookings_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_messaging_permissions,
            migrations.RunPython.noop,
        ),
    ]
