# Generated by Django 4.2.29 on 2026-05-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0023_messaging_permission_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="eprescribe_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
