# Generated by Claude on 2026-05-30

from django.db import migrations

# Default grant for the new prescribe capability, per role code. The real
# functional gate is the per-staff e-prescribe license flag; this is just the
# coarse permission default.
PRESCRIBE_BY_ROLE = {
    "admin": True,
    "physician": True,
    "nurse": False,
    "staff": False,
    "biller": False,
}

# Fallback refill-approve default per role code, used only when a role has no
# existing ``medications.manage`` value to inherit from (e.g. custom roles).
REFILL_APPROVE_BY_ROLE = {
    "admin": True,
    "physician": True,
    "nurse": True,
    "staff": False,
    "biller": False,
}


def add_medication_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")

    for role in StaffRole.objects.all():
        permissions = dict(role.security_permissions or {})

        # Preserve the current approver set: ``medications.refill.approve``
        # inherits the role's existing ``medications.manage`` value when set,
        # so regating approve/deny onto the new key changes nobody's access.
        manage_value = permissions.get("medications.manage")
        refill_default = (
            manage_value
            if manage_value is not None
            else REFILL_APPROVE_BY_ROLE.get(role.code, False)
        )

        permissions.setdefault("medications.refill.approve", refill_default)
        permissions.setdefault(
            "medications.prescribe", PRESCRIBE_BY_ROLE.get(role.code, False)
        )

        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0024_staff_eprescribe_enabled"),
    ]

    operations = [
        migrations.RunPython(
            add_medication_permissions,
            migrations.RunPython.noop,
        ),
    ]
