# Generated by Claude on 2026-06-01

from django.db import migrations

# Conservative fallbacks used only for custom roles that have no value to
# inherit from. Behaviour for the standard roles is preserved by inheriting
# the existing key each new permission was carved out of (see below).
DOCUMENTS_DELETE_BY_ROLE = {
    "admin": True,
    "physician": False,
    "nurse": True,
    "staff": True,
    "biller": False,
}

AUDIT_VIEW_BY_ROLE = {
    "admin": True,
    "physician": False,
    "nurse": False,
    "staff": False,
    "biller": False,
}


# Maps each newly carved-out key to the existing key it inherits from. The
# effective answer for the new key must equal the source key both at the role
# layer and at the per-staff override layer, otherwise staff who hold (or are
# denied) the source key via an individual override silently flip access.
SPLIT_KEYS = {
    "documents.delete": "documents.manage",
    "audit.view": "admin.facility.manage",
}

ROLE_FALLBACKS = {
    "documents.delete": DOCUMENTS_DELETE_BY_ROLE,
    "audit.view": AUDIT_VIEW_BY_ROLE,
}


def add_audit_and_document_delete_permissions(apps, schema_editor):
    StaffRole = apps.get_model("facilities", "StaffRole")
    Staff = apps.get_model("facilities", "Staff")

    # 1. Role defaults: each new key inherits the role's value for the key it
    # was carved out of, so re-gating onto the new key changes nobody's
    # role-level access. Custom roles missing the source key fall back to the
    # per-role default tables above.
    for role in StaffRole.objects.all():
        permissions = dict(role.security_permissions or {})

        for new_key, source_key in SPLIT_KEYS.items():
            source_value = permissions.get(source_key)
            default = (
                source_value
                if source_value is not None
                else ROLE_FALLBACKS[new_key].get(role.code, False)
            )
            permissions.setdefault(new_key, default)

        role.security_permissions = permissions
        role.save(update_fields=["security_permissions"])

    # 2. Per-staff overrides: effective permissions are role MERGED WITH a
    # sparse per-staff override map, applied only for keys explicitly present.
    # Mirror any individual grant OR denial of a source key onto the new key so
    # an override holder keeps the same effective answer. Copying the value
    # verbatim matters in BOTH directions: a ``False`` override (an explicit
    # denial) must propagate too, or the new key would fall back to the role
    # default and silently fail open.
    for staff in Staff.objects.all():
        overrides = dict(staff.security_overrides or {})
        original = dict(overrides)

        for new_key, source_key in SPLIT_KEYS.items():
            if source_key in overrides:
                overrides.setdefault(new_key, overrides[source_key])

        if overrides != original:
            staff.security_overrides = overrides
            staff.save(update_fields=["security_overrides"])


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0025_medication_eprescribe_permissions"),
    ]

    operations = [
        migrations.RunPython(
            add_audit_and_document_delete_permissions,
            migrations.RunPython.noop,
        ),
    ]
