# Generated by Django 4.2.29 on 2026-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0002_patientinsurancepolicy_coverage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecarrier",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
