# Generated by Django 4.2.29 on 2026-05-24 21:23

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_carriers_for_organizations(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    InsuranceCarrier = apps.get_model("insurance", "InsuranceCarrier")
    OrganizationInsuranceCarrierPreference = apps.get_model(
        "insurance",
        "OrganizationInsuranceCarrierPreference",
    )

    carriers = list(InsuranceCarrier.objects.filter(is_active=True))
    for organization in Organization.objects.all():
        for index, carrier in enumerate(carriers, start=1):
            OrganizationInsuranceCarrierPreference.objects.get_or_create(
                organization=organization,
                carrier=carrier,
                defaults={
                    "is_preferred": True,
                    "is_hidden": False,
                    "is_active": True,
                    "sort_order": index * 10,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0015_medication_allergy_permissions"),
        ("organizations", "0004_organizationpharmacypreference"),
        ("insurance", "0003_insurancecarrier_address_line_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInsuranceCarrierPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_preferences",
                        to="insurance.insurancecarrier",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_carrier_preferences",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "carrier__name"],
                "unique_together": {("organization", "carrier")},
            },
        ),
        migrations.CreateModel(
            name="FacilityInsuranceCarrierOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_overrides",
                        to="insurance.insurancecarrier",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_carrier_overrides",
                        to="facilities.facility",
                    ),
                ),
                (
                    "organization_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_overrides",
                        to="insurance.organizationinsurancecarrierpreference",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "sort_order",
                    "carrier__name",
                    "organization_preference__carrier__name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="facilityinsurancecarrieroverride",
            constraint=models.UniqueConstraint(
                fields=("facility", "organization_preference"),
                name="unique_facility_payer_org_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityinsurancecarrieroverride",
            constraint=models.UniqueConstraint(
                fields=("facility", "carrier"),
                name="unique_facility_local_payer_override",
            ),
        ),
        migrations.RunPython(
            seed_existing_carriers_for_organizations,
            migrations.RunPython.noop,
        ),
    ]
