# Generated by Django 4.2.29 on 2026-05-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_organizationfeeschedule_and_more"),
        ("insurance", "0004_organizationinsurancecarrierpreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinsurancecarrierpreference",
            name="fee_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_payer_preferences",
                to="billing.organizationfeeschedule",
            ),
        ),
    ]
