# Generated by Django 4.2.29 on 2026-05-29 00:58

from django.db import migrations, models
from django.db.models import Count


def demote_duplicate_primaries(apps, schema_editor):
    """Ensure at most one primary policy per patient before the constraint.

    Older code maintained this invariant in application logic, but a
    concurrent write could leave two primaries. Keep the most recently
    updated primary per patient and demote the rest so AddConstraint
    cannot fail on existing data.
    """
    Policy = apps.get_model("insurance", "PatientInsurancePolicy")
    patient_ids = (
        Policy.objects.filter(is_primary=True)
        .values("patient")
        .annotate(primary_count=Count("id"))
        .filter(primary_count__gt=1)
        .values_list("patient", flat=True)
    )
    for patient_id in patient_ids:
        keep = (
            Policy.objects.filter(patient_id=patient_id, is_primary=True)
            .order_by("-updated_at", "-id")
            .first()
        )
        if keep is None:
            continue
        Policy.objects.filter(patient_id=patient_id, is_primary=True).exclude(
            pk=keep.pk
        ).update(is_primary=False, coverage_order="secondary")


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0005_fee_schedule_redesign"),
    ]

    operations = [
        migrations.RunPython(demote_duplicate_primaries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="patientinsurancepolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("patient",),
                name="unique_primary_insurance_policy_per_patient",
            ),
        ),
    ]
