# Generated by Django 4.2.29 on 2026-06-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insurance",
            "0006_patientinsurancepolicy_unique_primary_insurance_policy_per_patient",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patientinsurancepolicy",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="patientinsurancepolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("patient", "carrier", "member_id"),
                name="unique_active_insurance_policy_per_member",
            ),
        ),
    ]
