# Generated by Django 4.2.29 on 2026-07-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_seed_system_org_roles"),
        ("facilities", "0026_audit_documents_delete_permissions"),
        ("insurance", "0007_alter_patientinsurancepolicy_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecarrier",
            name="directory_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="last_directory_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="owning_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_insurance_carriers",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="owning_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_insurance_carriers",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="insurancecarrier",
            name="source",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("imported", "Imported"),
                    ("directory", "Directory"),
                ],
                default="directory",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="insurancecarrier",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("owning_facility__isnull", False),
                    ("owning_organization__isnull", False),
                    _negated=True,
                ),
                name="carrier_has_at_most_one_tenant_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="insurancecarrier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("directory_source", "external_id"),
                name="unique_carrier_external_directory_id",
            ),
        ),
    ]
