# Generated by Django 4.2.29 on 2026-05-22 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0015_document_category_system_defaults"),
        ("facilities", "0013_clinical_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAllergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergen", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("food", "Food"),
                            ("environmental", "Environmental"),
                            ("latex", "Latex"),
                            ("contrast", "Contrast"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("reaction", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life Threatening"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("resolved", "Resolved"),
                            ("entered_in_error", "Entered in Error"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patient_allergies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_allergies",
                        to="facilities.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allergies",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_patient_allergies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient allergies",
                "ordering": ["-is_active", "allergen", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "patient", "-is_active", "allergen"],
                        name="allergies_p_facilit_681514_idx",
                    ),
                    models.Index(
                        fields=["facility", "status", "category"],
                        name="allergies_p_facilit_f44756_idx",
                    ),
                ],
            },
        ),
    ]
